version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app:cached
      - ../node_modules:/app/node_modules
    command: sleep infinity
volumes:
  node_modules:
