name: Publish if new version

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  check_version:
    name: Check Version tag
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.tag_check.outputs.exists }}
      version: v${{ steps.version.outputs.value }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version package.json -r"

      - uses: mukunku/tag-exists-action@v1.0.0
        id: tag_check
        with:
          tag: v${{ steps.version.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.tag_check.outputs.exists }}
  deploy:
    runs-on: ubuntu-latest
    needs: check_version
    if: needs.check_version.outputs.tag_exists == 'false'
    env:
      CLASPRC_ACCESS_TOKEN: ${{ secrets.CLASPRC_ACCESS_TOKEN }}
      CLASPRC_CLIENT_ID: ${{ secrets.CLASPRC_CLIENT_ID }}
      CLASPRC_CLIENT_SECRET: ${{ secrets.CLASPRC_CLIENT_SECRET }}
      CLASPRC_EXPIRY_DATE: ${{ secrets.CLASPRC_EXPIRY_DATE }}
      CLASPRC_ID_TOKEN: ${{ secrets.CLASPRC_ID_TOKEN }}
      CLASPRC_REFRESH_TOKEN: ${{ secrets.CLASPRC_REFRESH_TOKEN }}
      CLASP_SCRIPT_ID: ${{ secrets.CLASP_SCRIPT_ID }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Setup
        shell: bash
        run: yarn install --frozen-lockfile

      - name: Build
        shell: bash
        run: yarn build

      - name: Create clasp files
        run: bash scripts/setup.sh

      - name: Upload files
        run: npx @google/clasp push --force

      - name: Deploy
        run: npx @google/clasp deploy -i $DEPLOYMENT_ID -d ${{ needs.check_version.outputs.version }}

      - name: Add tag if the version tag doesn't exist
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ needs.check_version.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
