name: Release Tag

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version package.json -r"

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ steps.version.outputs.value }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
