name: Run Test

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Setup
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Build
        shell: bash
        run: yarn build
      - name: Test
        shell: bash
        run: yarn test
      - name: Lint
        shell: bash
        run: yarn lint
